__all__ = ['ProcessNode']


from target import Target as tg


class ProcessNode:
    def __init__(self, id: int, time: int, type: int, subtype: int, pid: int, ppid: int, cmdLine: str, processName: str):
        self.id=id
        self.time=time
        self.type=type
        self.subtype=subtype
        self.pid=pid
        self.ppid = ppid
        self.cmdLine = cmdLine
        self.processName=processName


        # init tags
        self.sTag: float = 0.0
        # benign
        self.iTag: float = 0.0
        #
        self.cTag: float = 0.0

        if self.ppid==-1:
            # unknown parent
            self.sTag = tg.get_stag_dangerous()
        elif self.ppid==0:
            # process generated by root
            self.sTag=tg.get_stag_benign()
        else:
            from globals import GlobalVariable as gv
            parent_id=gv.get_processNode_by_pid(self.ppid)
            parent_node=gv.get_processNode(parent_id)
            if not parent_node:
                # parent node not exist or has been released, then this node is not valid
                self.sTag = tg.get_stag_dangerous()
                self.iTa = tg.get_itag_dangerous()
                self.cTag = tg.get_ctag_dangerous()
            else:
                self.sTag = parent_node.sTag
                self.iTag = parent_node.iTag
                self.cTag = parent_node.cTag

    def get_matrix_array(self, padding: 4):
        if padding < 4:
            return None

        return [self.subtype, self.sTag, self.iTag, self.cTag]+[0]*(padding-4)

